server:
  http_addr: ":8080"
  env: dev
  log_level: debug
  enable_pprof: false

mysql:
  user: root
  password: 123456
  host: 127.0.0.1
  port: 3306
  database: xinyu_blog
  charset: utf8mb4
  show_sql: true
  max_open: 50
  max_idle: 10

redis:
  addr: 127.0.0.1:6379
  password: ""
  db: 0
  max_idle: 10
  max_open: 50

jwt:
  secret: "your-secret-key"   # JWT 密钥
  expire: 3600                # 过期时间（1小时）